version: 3
servicecs:
  catalogue_ms:
    build: ./backend/catalogue_ms
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0.32
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      -./db:/docker-entrypoint-initdb.d/:ro